# -*- coding: utf-8 -*-
lista_desierto= [
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                             PPP                                          P",
        "P                             PPP                                          P",
        "P                             PPP                                          P",
        "P                     PPPPPPPPPPPPPPPPPPP                                  P",
        "P                     PPPPPPPPPPPPPPPPPPP                                  P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                PPP       P",
        "P                                                                PPP       P",
        "P                                                                PPP       P",
        "P                                                            PPPPPPPPPPP   P",
        "P                                                            PPPPPPPPPPP   P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                           PPPPPPPPPPP                                    P",
        "P                           PPPPPPPPPPP                                    P",
        "PPPPP                                                                      P",
        "PPPPP                                                                      P",
        "P PPP                                                                      P",
        "P PPPPPPPPP                                        PPPPPPPPPPP             P",
        "PPPPPPPPPPP                                         PPPPPPPPPP             P",
        "P                                                                          P",
        "P                                                                          P",
        "P                 PPPPP                                                    P",
        "P                 PPPPP                                                    P",
        "P               PPPPPPPPP                                                  P",
        "P               PPPPPPPPP                                                  P",
        "P                                                                          P",
        "P                                          PPPPPPPPPP                      P",
        "P                                          PPPPPPPPPP                 PPPPPP",
        "P                                                                     PPPPPP",
        "P                                                                     PPPPPP",
        "P                                                                     PPPPPP",
        "P                    PPPPPPPPPP                                  PPPPPPPPPPP",
        "P                    PPPPPPPPPP                                  PPPPPPPPPPP",
        "P                    PPPPPPPPPP                                 PPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",]

lista_bosque=[
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPP                                                                      P",
        "PPPPP                                                                      P",
        "PPPPP                                                                      P",
        "PPPPPPPPP                  PPPPPPPP                                        P",
        "PPPPPPPPP                  PPPPPPPP                                        P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPPPPP                                              PPPPPPPP    P",
        "PPPPPPPPPPPPPPPPP                                              PPPPPPPP    P",
        "PPPPPPPPPPPPPPPPP                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                              PPPP                        P",
        "P                                              PPPP                        P",
        "P                                              PPPP                        P",
        "P                            PPPPPPPPPPPPPPPPPPPPPP                        P",
        "P                            PPPPPPPPPPPPPPPPPPPPPP                        P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                  PPPPPPPPP",
        "P                                                                  PPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                   PPPP                                                   P",
        "P                   PPPP                                                   P",
        "P                   PPPP                                                   P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",]

lista_kawai=[
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPP                        PPPPPP                        PPPPPPPPPPP",
        "PPPPPPPPPPP                        PPPPPP                        PPPPPPPPPPP",
        "P                                  PPPPPP                                  P",
        "P                                  PPPPPP                                  P",
        "P                                  PPPPPP                                  P",
        "P                                  PPPPPP                                  P",
        "P                                  PPPPPP                                  P",
        "P                                  PPPPPP                                  P",
        "P                          PPPPPPPPPPPPPPPPPPPPPP                          P",
        "P                          PPPPPPPPPPPPPPPPPPPPPP                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPPP                                                            P",
        "PPPPPPPPPPPPPPP                                              PPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPP                                              PPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPP                                              PPPPPPPPPPPPPPP",
        "P                                                            PPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                PPPPPPPPPP                                P",
        "P                                PPPPPPPPPP                                P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P          PPPPPPPPPPPPPPPPP                   PPPPPPPPPPPPPPPPP           P",
        "P          PPPPPPPPPPPPPPPPP                   PPPPPPPPPPPPPPPPP           P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP"]

lista_planetas=[
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P                                     PPP                                  P",
        "P            PPPPPP                   PPP                        PPPPPP    P",
        "P            PPPPPP             PPPPPPPPPPPPPPP                  PPPPPP    P",
        "P            PPPPPP             PPPPPPPPPPPPPPP                  PPPPPP    P",
        "P                               PPPPPPPPPPPPPPP                            P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPPPP                                            PPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPP                                            PPPPPPPPPPPPPPPP",
        "PPPPPPPPPPPPPPPP                                            PPPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                       PPPPPP                 PPPPPP                      P",
        "P                       PPPPPP                 PPPPPP                      P",
        "P                       PPPPPP                 PPPPPP                      P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P    PPP                                                            PPP    P",
        "P    PPP                                                            PPP    P",
        "P    PPP                                                            PPP    P",
        "P                                                                          P",
        "P                          PPPPPPPPPPPPPPPPPPPPPPPP                        P",
        "P                          PPPPPPPPPPPPPPPPPPPPPPPP                        P",
        "P                          PPPPPPPPPPPPPPPPPPPPPPPP                        P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",]

lista_ciudad=[
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                              PPPPPPPPPPPPPPPPPPPPPPPPPPP                 P",
        "P                              PPPPPPPPPPPPPPPPPPPPPPPPPPP                 P",
        "P                              PPPPPPPPPPPPPPPPPPPPPPPPPPP                 P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPPPP                                                             P",
        "PPPPPPPPPPPPPP                                                             P",
        "PPPPPPPPPPPPPP                                                             P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                              PPPPPPPPPPPPP",
        "P                                                              PPPPPPPPPPPPP",
        "P                                                              PPPPPPPPPPPPP",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                              PPPPPPPPPPPPPP                              P",
        "P                              PPPPPPPPPPPPPP                              P",
        "P                              PPPPPPPPPPPPPP                              P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                                                          P",
        "PPPPPPPPPPPP                                                               P",
        "PPPPPPPPPPPP                                                               P",
        "P                                                                          P",
        "P                                                                          P",
        "P                                        PPPPPP                            P",
        "P                                        PPPPPP                            P",
        "P                                        PPPPPP                            P",
        "P                                     PPPPPPPPPPPP                         P",
        "P                                     PPPPPPPPPPPP                         P",
        "P                                     PPPPPPPPPPPP                         P",
        "PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP",]
